"use client";

import { useEffect, useState } from "react";
import { CalendarClock, LogOut } from "lucide-react";
import { supabase } from "@/app/lib/supabase/client";
import PremiumButton from "@/app/components/ui/PremiumButton";

type EventRow = { id: string; name: string; effective_status: string; starts_at: string; ends_at: string; simulados: { title?: string } | null };

export default function ProfessorEventosClient() {
  const [events, setEvents] = useState<EventRow[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { void supabase.auth.getSession().then(async ({ data }) => { if (!data.session) return; const response = await fetch("/api/professor/events", { headers: { Authorization: `Bearer ${data.session.access_token}` } }); const json = await response.json(); if (json.ok) setEvents(json.events); setLoading(false); }); }, []);
  const groups = ["active", "scheduled", "closed", "archived"].map((status) => ({ status, items: events.filter((event) => event.effective_status === status) })).filter((group) => group.items.length);
  const labels: Record<string, string> = { active: "Em andamento", scheduled: "Agendados", closed: "Encerrados", archived: "Histórico arquivado" };
  return <main className="min-h-dvh px-4 py-8 text-slate-900 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><header className="relative overflow-hidden rounded-[2rem] border border-slate-200 bg-[radial-gradient(circle_at_88%_12%,rgba(249,115,22,0.13),transparent_30%),linear-gradient(135deg,#ffffff,#f8fafc)] p-6 shadow-[0_24px_70px_rgba(15,23,42,0.09)] ring-1 ring-white sm:p-8"><div className="relative flex items-start justify-between gap-6"><div><p className="et-teacher-eyebrow">Área do professor</p><h1 className="mt-3 text-[clamp(30px,4vw,46px)] font-bold leading-[1.08] tracking-[-0.04em] text-slate-950">Meus eventos</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Acompanhe participantes, resultados oficiais e revisão pedagógica em um ambiente claro e organizado.</p></div><PremiumButton variant="secondary" onClick={() => void supabase.auth.signOut().then(() => location.assign("/login"))} icon={<LogOut size={16} />}>Sair</PremiumButton></div></header>{loading ? <div className="mt-8 rounded-3xl border border-slate-200 bg-white p-8 text-sm leading-5 text-slate-500 shadow-sm">Carregando eventos...</div> : groups.map((group) => <section key={group.status} className="mt-9"><div className="flex items-center gap-3"><span className="h-2.5 w-2.5 rounded-full bg-orange-500 shadow-[0_0_0_5px_rgba(249,115,22,0.12)]" /><h2 className="text-lg font-semibold leading-7 text-slate-800">{labels[group.status]}</h2><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-500">{group.items.length}</span></div><div className="mt-4 grid gap-5 md:grid-cols-2">{group.items.map((event) => <article key={event.id} className="group rounded-[1.7rem] border border-slate-200 bg-white p-6 shadow-[0_14px_40px_rgba(15,23,42,0.06)] ring-1 ring-white transition duration-300 hover:-translate-y-0.5 hover:border-orange-200 hover:shadow-[0_22px_55px_rgba(15,23,42,0.10)]"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-orange-50 text-orange-600 ring-1 ring-orange-100"><CalendarClock size={21} /></div><h3 className="mt-5 text-xl font-bold leading-7 text-slate-950">{event.name}</h3><p className="mt-2 text-sm leading-5 text-slate-500">{event.simulados?.title || "Simulado ainda não vinculado"} · {labels[event.effective_status]}</p><div className="mt-6"><PremiumButton href={`/professor/eventos/${event.id}`} variant={event.effective_status === "active" ? "primary" : "secondary"}>{event.effective_status === "archived" ? "Consultar histórico" : "Abrir Evento"}</PremiumButton></div></article>)}</div></section>)}</div></main>;
}
