"use client";

import { useEffect, useState } from "react";
import { CalendarClock, Users } from "lucide-react";
import { supabase } from "@/app/lib/supabase/client";
import PremiumButton from "@/app/components/ui/PremiumButton";

type Row = { id: string; representative_attempt_id: string | null; result_released_at: string | null; attempts: Array<{ id: string; status: string }>; simulado_events: { id: string; name: string; starts_at: string; ends_at: string; simulado_id: string | null; effective_status: string; simulados?: { title?: string } | null; simulado_event_professors: Array<{ professors: { name: string } | null }> } };

export default function MeusEventosClient() {
  const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { void supabase.auth.getSession().then(async ({ data }) => { if (!data.session) return; const response = await fetch("/api/student/events", { headers: { Authorization: `Bearer ${data.session.access_token}` } }); const json = await response.json(); if (json.ok) setRows(json.events); setLoading(false); }); }, []);
  return <main className="min-h-full bg-slate-50 px-4 py-8 md:px-8"><div className="mx-auto max-w-6xl"><p className="text-xs font-black uppercase tracking-[0.22em] text-orange-600">Área do aluno</p><h1 className="mt-2 text-3xl font-black text-slate-950">Meus Eventos</h1>{loading ? <p className="mt-8 text-slate-500">Carregando...</p> : rows.length ? <div className="mt-8 grid gap-5 md:grid-cols-2">{rows.map((row) => { const running = row.attempts.some((attempt) => attempt.status === "in_progress"); const completed = row.attempts.some((attempt) => ["completed", "disqualified", "expired"].includes(attempt.status)); const individual = running ? "Em andamento" : completed ? (row.result_released_at ? "Resultado disponível" : "Concluído · aguardando resultado") : row.simulado_events.effective_status === "closed" ? "Não realizado" : "Não iniciado"; const professors = row.simulado_events.simulado_event_professors.map((item) => item.professors?.name).filter(Boolean).join(", ") || "A definir"; return <article key={row.id} className="rounded-[1.7rem] border border-slate-200 bg-white p-6 shadow-sm"><CalendarClock className="text-orange-500" /><h2 className="mt-4 text-xl font-black text-slate-950">{row.simulado_events.name}</h2><p className="mt-2 text-sm text-slate-500">Evento: {row.simulado_events.effective_status} · Você: {individual}</p><p className="mt-2 flex items-center gap-2 text-sm text-slate-600"><Users size={15} className="text-orange-500" />{professors}</p><p className="mt-2 text-xs text-slate-500">{new Intl.DateTimeFormat("pt-BR", { timeZone: "America/Sao_Paulo", dateStyle: "short", timeStyle: "short" }).format(new Date(row.simulado_events.starts_at))} · Brasília</p><div className="mt-5"><PremiumButton href={`/meus-eventos/${row.simulado_events.id}`} variant={running ? "primary" : "secondary"}>{running ? "Continuar" : row.result_released_at ? "Ver resultado" : "Abrir Evento"}</PremiumButton></div></article>; })}</div> : <p className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 text-slate-500">Você ainda não participa de nenhum Evento.</p>}</div></main>;
}
